# Generated by Django 5.2.8 on 2025-12-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('duracion_horas', models.IntegerField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='fichas.programa')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'db_table': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_aprendizaje', to='competencias.competencia')),
            ],
            options={
                'verbose_name': 'Resultado de Aprendizaje',
                'verbose_name_plural': 'Resultados de Aprendizaje',
                'db_table': 'resultados_aprendizaje',
            },
        ),
    ]
