# Generated by Django 5.2.8 on 2025-12-03 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INASISTENCIAS', 'Inasistencias'), ('EVALUACIONES', 'Juicios Evaluativos')], max_length=20)),
                ('archivo', models.FileField(upload_to='imports/%Y/%m/')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('registros_importados', models.IntegerField(default=0)),
                ('registros_error', models.IntegerField(default=0)),
                ('registros_omitidos', models.IntegerField(default=0)),
                ('log_errores', models.TextField(blank=True, null=True)),
                ('tiempo_proceso', models.FloatField(help_text='Segundos', null=True)),
                ('ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fichas.ficha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Importado',
                'verbose_name_plural': 'Archivos Importados',
                'db_table': 'archivos_importados',
                'ordering': ['-fecha_importacion'],
            },
        ),
    ]
