# Generated by Django 5.2.8 on 2025-12-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprendices', '0001_initial'),
        ('competencias', '0001_initial'),
        ('importador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuicioEvaluativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juicio', models.CharField(choices=[('APROBADO', 'Aprobado'), ('NO_APROBADO', 'No Aprobado'), ('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso')], max_length=20)),
                ('fecha_evaluacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('importado_desde_excel', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicios_evaluativos', to='aprendices.aprendiz')),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importador.archivoimportado')),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.resultadoaprendizaje')),
            ],
            options={
                'verbose_name': 'Juicio Evaluativo',
                'verbose_name_plural': 'Juicios Evaluativos',
                'db_table': 'juicios_evaluativos',
                'indexes': [models.Index(fields=['aprendiz', 'juicio'], name='juicios_eva_aprendi_a9c490_idx')],
                'unique_together': {('aprendiz', 'resultado_aprendizaje', 'fecha_evaluacion')},
            },
        ),
    ]
