# Generated by Django 5.2.8 on 2025-11-28 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_horas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('numero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('programa', models.CharField(blank=True, max_length=200)),
                ('instructor', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('documento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_formacion', models.CharField(choices=[('INDUCCION', 'INDUCCIÓN'), ('FORMACION', 'FORMACIÓN'), ('POR_CERTIFICAR', 'POR CERTIFICAR'), ('CERTIFICADO', 'CERTIFICADO'), ('APLAZADO', 'APLAZADO'), ('REINGRESADO', 'REINGRESADO'), ('DESERTO', 'DESERTO')], default='FORMACION', max_length=30)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='aprendices.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='ActaComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('contenido', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/')),
                ('creado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aprendices.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('reportado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='aprendices.aprendiz')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='aprendices.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='aprendices.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='AprendizResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('APROBADO', 'APROBADO'), ('NO_APROBADO', 'NO APROBADO'), ('PENDIENTE', 'PENDIENTE')], default='PENDIENTE', max_length=30)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_aprendiz', to='aprendices.aprendiz')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendices_resultado', to='aprendices.resultadoaprendizaje')),
            ],
            options={
                'unique_together': {('aprendiz', 'resultado')},
            },
        ),
    ]
