# Generated by Django 5.2.8 on 2026-03-23 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del Centro')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Centro')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Formación',
                'verbose_name_plural': 'Centros de Formación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Competencia')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre de la Competencia')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Número de Ficha')),
                ('programa', models.CharField(default='Por definir', max_length=200, verbose_name='Programa de Formación')),
                ('instructor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instructor Principal')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='aprendices.centroformacion', verbose_name='Centro de Formación')),
            ],
            options={
                'verbose_name': 'Ficha de Caracterización',
                'verbose_name_plural': 'Fichas de Caracterización',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Documento de Identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('estado_formacion', models.CharField(choices=[('EN_FORMACION', 'En Formación'), ('ETAPA_LECTIVA', 'Etapa Lectiva'), ('ETAPA_PRODUCTIVA', 'Etapa Productiva'), ('POR_CERTIFICAR', 'Por Certificar'), ('CERTIFICADO', 'Certificado'), ('CANCELADO', 'Cancelado'), ('RETIRO_VOLUNTARIO', 'Retiro Voluntario'), ('APLAZAMIENTO', 'Aplazamiento')], default='EN_FORMACION', max_length=30, verbose_name='Estado de Formación')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('fecha_fin_lectiva', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Etapa Lectiva')),
                ('fecha_fin_productiva', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Etapa Productiva')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprendices', to='aprendices.ficha', verbose_name='Ficha de Caracterización')),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActaComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Comité')),
                ('contenido', models.TextField(verbose_name='Contenido del Acta')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='aprendices.ficha', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Acta de Comité',
                'verbose_name_plural': 'Actas de Comité',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Inasistencia')),
                ('justificada', models.BooleanField(default=False, verbose_name='¿Justificada?')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('reportado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reportado Por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='aprendices.aprendiz', verbose_name='Aprendiz')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aprendices.ficha', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Resultado')),
                ('nombre', models.CharField(max_length=500, verbose_name='Descripción del Resultado')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='aprendices.competencia', verbose_name='Competencia')),
            ],
            options={
                'verbose_name': 'Resultado de Aprendizaje',
                'verbose_name_plural': 'Resultados de Aprendizaje',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AprendizResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('NO_APROBADO', 'No Aprobado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha', models.DateField(verbose_name='Fecha de Evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juicios', to='aprendices.aprendiz', verbose_name='Aprendiz')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendices.resultadoaprendizaje', verbose_name='Resultado de Aprendizaje')),
            ],
            options={
                'verbose_name': 'Juicio Evaluativo',
                'verbose_name_plural': 'Juicios Evaluativos',
                'ordering': ['-fecha'],
                'unique_together': {('aprendiz', 'resultado')},
            },
        ),
        migrations.CreateModel(
            name='RolAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(choices=[('SUBDIRECTOR', 'Subdirector'), ('COORDINADOR_ACADEMICO', 'Coordinador Académico'), ('COORDINADOR_FORMACION', 'Coordinador de Formación'), ('COORDINADOR_MISIONAL', 'Coordinador Misional'), ('COORDINADOR_ADMINISTRATIVO', 'Coordinador Administrativo')], max_length=50, verbose_name='Tipo de Rol')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Rol')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin del Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='aprendices.centroformacion', verbose_name='Centro de Formación')),
                ('usuario', models.ForeignKey(help_text='Usuario asociado a este rol', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol Administrativo',
                'verbose_name_plural': 'Roles Administrativos',
                'ordering': ['-activo', 'centro', 'tipo_rol'],
                'unique_together': {('usuario', 'tipo_rol', 'centro', 'activo')},
            },
        ),
    ]
