# Generated by Django 5.2.8 on 2025-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_fin_lectiva',
            field=models.DateField(blank=True, help_text='Fecha fin etapa lectiva', null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_fin_productiva',
            field=models.DateField(blank=True, help_text='Fecha fin etapa productiva', null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='estado_formacion',
            field=models.CharField(choices=[('EN_FORMACION', 'EN FORMACIÓN'), ('ETAPA_PRODUCTIVA', 'ETAPA PRODUCTIVA'), ('POR_CERTIFICAR', 'POR CERTIFICAR'), ('CERTIFICADO', 'CERTIFICADO'), ('CANCELADO', 'CANCELADO'), ('DESERTADO', 'DESERTADO'), ('APLAZADO', 'APLAZADO'), ('REINGRESADO', 'REINGRESADO')], default='EN_FORMACION', max_length=30),
        ),
    ]
