# Generated by Django 5.2.8 on 2026-03-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoo', models.CharField(default='PENDIENTE', max_length=50)),
                ('porcentaje', models.IntegerField(default=0)),
                ('mensaje', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
