# Generated by Django 5.2.8 on 2026-03-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_progresoimportacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgresoImportacion',
        ),
    ]
