# Generated by Django 5.2.8 on 2026-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_delete_progresoimportacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='estado_formacion',
            field=models.CharField(choices=[('EN_FORMACION', 'En Formación'), ('ETAPA_LECTIVA', 'Etapa Lectiva'), ('ETAPA_PRODUCTIVA', 'Etapa Productiva'), ('POR_CERTIFICAR', 'Por Certificar'), ('CERTIFICADO', 'Certificado'), ('CANCELADO', 'Cancelado'), ('RETIRO_VOLUNTARIO', 'Retiro Voluntario'), ('APLAZAMIENTO', 'Aplazamiento'), ('TRASLADADO', 'Trasladado')], default='EN_FORMACION', max_length=30, verbose_name='Estado de Formación'),
        ),
    ]
