# Generated by Django 5.2.8 on 2025-12-03 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PEP', 'Permiso Especial de Permanencia')], default='CC', max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_formacion', models.CharField(choices=[('EN_FORMACION', 'En Formación'), ('POR_CERTIFICAR', 'Por Certificar'), ('CERTIFICADO', 'Certificado'), ('RETIRO_VOLUNTARIO', 'Retiro Voluntario'), ('CANCELADO', 'Cancelado'), ('CONDICIONADO', 'Condicionado'), ('VIGENCIA_VENCIDA', 'Vigencia Vencida')], default='EN_FORMACION', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprendices', to='fichas.ficha')),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
                'db_table': 'aprendices',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
