# Generated by Django 5.2.9 on 2025-12-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('FAILED_LOGIN', 'Intento de Login Fallido')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'db_table': 'historial_accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COORDINADOR', 'Coordinador Académico'), ('INSTRUCTOR', 'Instructor'), ('CONSULTA', 'Solo Consulta')], default='INSTRUCTOR', max_length=20)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('centro_formacion', models.CharField(blank=True, max_length=200)),
                ('recibir_alertas_email', models.BooleanField(default=True)),
                ('recibir_recordatorios', models.BooleanField(default=True)),
                ('frecuencia_recordatorios', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal')], default='SEMANAL', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'perfiles_usuario',
            },
        ),
    ]
