# Generated by Django 5.2.8 on 2025-12-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprendices', '0001_initial'),
        ('importador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('justificada', models.BooleanField(default=False)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('soporte_adjunto', models.FileField(blank=True, null=True, upload_to='inasistencias/soportes/')),
                ('importado_desde_excel', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inasistencias', to='aprendices.aprendiz')),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importador.archivoimportado')),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'db_table': 'inasistencias',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['aprendiz', 'fecha'], name='inasistenci_aprendi_3c050b_idx'), models.Index(fields=['justificada'], name='inasistenci_justifi_e36c43_idx')],
                'unique_together': {('aprendiz', 'fecha')},
            },
        ),
    ]
