# Generated by Django 5.2.9 on 2025-12-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasistencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inasistencia',
            name='cant_horas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inasistencia',
            name='instructor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
