# Generated by Django 5.2.8 on 2025-12-03 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('ESPECIALIZACION', 'Especialización Tecnológica'), ('OPERARIO', 'Operario')], max_length=50)),
                ('duracion_meses', models.IntegerField(help_text='Duración total en meses')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_lectiva', models.DateField()),
                ('fecha_fin_practica', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('instructor_lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_lideradas', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fichas.programa')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'db_table': 'fichas',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['numero'], name='fichas_numero_8ea8d4_idx'), models.Index(fields=['estado', 'fecha_fin_lectiva'], name='fichas_estado_4cb07a_idx')],
            },
        ),
    ]
